### ISSUE TITLE
old issues from apps repo

### ISSUE THREAD

**Issue by georgehrke** [owncloudarchive/calendar#1]
We need to keep in mind there are still reports in the old issue tracker in the apps repo: https://github.com/owncloud/apps/issues?labels=app%3Acalendar&milestone=&page=1&state=open

**Comment by AbdealiJK** [comment]
You may want to use https://github-issue-mover.appspot.com/ which would help move the remaining issues over to this repo (it works great)

**Comment by DeepDiver1975** [comment]
we should close the issues in the apps repo
