### ISSUE TITLE
Important: move this repo to the owncloud archive organization

### ISSUE THREAD

**Issue by georgehrke** [owncloudarchive/calendar#1037]
... and rename calendar-rework to calendar

cc @DeepDiver1975

**Comment by georgehrke** [comment]
We should do this shortly prior to the ownCloud 9 release.
I actually don't see a need to provide the calendar for ownCloud <9 via the app store then, so the releases in this repo don't matter.

**Comment by DeepDiver1975** [comment]
People still want to install oc<9 and will expect calendar to be installable.

**Comment by DeepDiver1975** [comment]
From appstore as well as from git using stable branches.

**Comment by georgehrke** [comment]
we can just publish the releases in the old versions in the rework repo.
Regarding the git stable branches: There are test files in there, they are simply not supposed for production.

**Comment by DeepDiver1975** [comment]
okay - contacts just git successfully moved to the archive organization - let's see what we can do here ...

**Comment by RealRancor** [comment]
Just make sure that it is clear that both, the new contacts and calendar repositories are both for the rewrite. If that's not clear you will still get new issues for the old apps ending up there.

**Comment by DeepDiver1975** [comment]
> If that's not clear you will still get new issues for the old apps ending up there.

THX for the pointer - we should state this clearly in the readme as well as the issue template

**Comment by georgehrke** [comment]
I will copy over the old releases.

**Comment by georgehrke** [comment]
> I will copy over the old releases.

Or do we simply want to point apps.owncloud.com to owncloudarchive/calendar ?

**Comment by georgehrke** [comment]
@karlitschek @cmonteroluque please update your build scripts. :)
The calendar and the contacts repo won't have stable* branches anymore. Furthermore I think applying the core tags to these repos is not necessary anymore.

**Comment by DeepDiver1975** [comment]
I will simply point to owncloudarchive

**Comment by georgehrke** [comment]
awesome thx!

**Comment by karlitschek** [comment]
This is most likely fine. The calendar is no longer in 8.x and newer. And 7 is out of support in the next few weeks. So this is fine probably.

**Comment by DeepDiver1975** [comment]
done

**Comment by georgehrke** [comment]
thx :)
