### ISSUE TITLE
Automated external ICS import

### ISSUE THREAD

**Issue by jbtbnl** [owncloudarchive/calendar#344]
A lot of calendar servers support a periodical import of an external ICS file. It enables one to view a shared calendar within ownCloud.

@georgehrke has already built a simple PHP script for this, see  https://github.com/owncloud/calendar/pull/321#issuecomment-33801455

This function should get an entry the settings menu of the Calendar app to enable all users to make use of it.

**Comment by MrTimscampi** [comment]
Any news on this ?

**Comment by forteller** [comment]
So, is it still not possible to use a webcal with ownCloud calendar?

I would really love to get all the events I'm invited to in Facebook automatically imported into oC, so I wouldn't have to log in to Facebook all the time to check.

**Comment by mdosch** [comment]
Am also waiting for this feature for a long time now. It's not even on the roadmap as it's not linked to any milestone.

**Comment by DeepDiver1975** [comment]
Please reopen this in https://github.com/owncloud/calendar - this repo holds the old and discontinued calendar app - THX
